use crate::model::{Language, Rule, Severity};

pub const RULES: &[Rule] = &[
    Rule {
        code: "RS001",
        lang: Some(Language::Rust),
        severity: Severity::Warn,
        principle: "immutable values",
        title: "mutable local binding (`let mut`)",
    },
    Rule {
        code: "RS002",
        lang: Some(Language::Rust),
        severity: Severity::Error,
        principle: "explicit state transitions",
        title: "module-level mutable / shared-interior global",
    },
    Rule {
        code: "RS003",
        lang: Some(Language::Rust),
        severity: Severity::Error,
        principle: "typed errors",
        title: "panic-based control flow (`unwrap`/`expect`/`panic!`)",
    },
    Rule {
        code: "RS004",
        lang: Some(Language::Rust),
        severity: Severity::Warn,
        principle: "illegal states excluded by types",
        title: "wildcard match arm defeats exhaustiveness",
    },
    Rule {
        code: "RS005",
        lang: Some(Language::Rust),
        severity: Severity::Warn,
        principle: "typed errors",
        title: "untyped/erased error in a signature",
    },
    Rule {
        code: "RS006",
        lang: Some(Language::Rust),
        severity: Severity::Warn,
        principle: "pure transformations",
        title: "interior mutability outside a stateful module",
    },
    Rule {
        code: "RS007",
        lang: Some(Language::Rust),
        severity: Severity::Warn,
        principle: "effects pushed outward",
        title: "direct stdout/stderr effect in library code",
    },
    Rule {
        code: "RS008",
        lang: Some(Language::Rust),
        severity: Severity::Warn,
        principle: "explicit outputs",
        title: "`&mut self` method returning unit",
    },
    Rule {
        code: "RS009",
        lang: Some(Language::Rust),
        severity: Severity::Error,
        principle: "illegal states excluded by types",
        title: "`unsafe` block",
    },
    Rule {
        code: "TS001",
        lang: Some(Language::TypeScript),
        severity: Severity::Error,
        principle: "immutable values",
        title: "`var` declaration",
    },
    Rule {
        code: "TS002",
        lang: Some(Language::TypeScript),
        severity: Severity::Warn,
        principle: "immutable values",
        title: "mutable `let` binding",
    },
    Rule {
        code: "TS003",
        lang: Some(Language::TypeScript),
        severity: Severity::Error,
        principle: "explicit state transitions",
        title: "module-level mutable binding",
    },
    Rule {
        code: "TS004",
        lang: Some(Language::TypeScript),
        severity: Severity::Warn,
        principle: "pure transformations",
        title: "in-place array mutation",
    },
    Rule {
        code: "TS005",
        lang: Some(Language::TypeScript),
        severity: Severity::Warn,
        principle: "explicit inputs",
        title: "`any` escapes the type system",
    },
    Rule {
        code: "TS006",
        lang: Some(Language::TypeScript),
        severity: Severity::Warn,
        principle: "typed errors",
        title: "`throw` as control flow",
    },
    Rule {
        code: "TS007",
        lang: Some(Language::TypeScript),
        severity: Severity::Error,
        principle: "composition",
        title: "React / JSX dependency",
    },
    Rule {
        code: "TS008",
        lang: Some(Language::TypeScript),
        severity: Severity::Warn,
        principle: "effects pushed outward",
        title: "direct console effect in library code",
    },
    Rule {
        code: "TS009",
        lang: Some(Language::TypeScript),
        severity: Severity::Warn,
        principle: "explicit inputs",
        title: "ambient impurity (clock / randomness / env) read inside pure code",
    },
    Rule {
        code: "TS010",
        lang: Some(Language::TypeScript),
        severity: Severity::Warn,
        principle: "illegal states excluded by types",
        title: "non-null assertion (`!`) suppresses a real case",
    },
    Rule {
        code: "DA001",
        lang: Some(Language::Dart),
        severity: Severity::Warn,
        principle: "immutable values",
        title: "`var` binding instead of `final`",
    },
    Rule {
        code: "DA002",
        lang: Some(Language::Dart),
        severity: Severity::Error,
        principle: "explicit state transitions",
        title: "top-level mutable variable",
    },
    Rule {
        code: "DA003",
        lang: Some(Language::Dart),
        severity: Severity::Warn,
        principle: "immutable values",
        title: "mutable (non-`final`) instance field",
    },
    Rule {
        code: "DA004",
        lang: Some(Language::Dart),
        severity: Severity::Warn,
        principle: "immutable values",
        title: "`late` non-final binding",
    },
    Rule {
        code: "DA005",
        lang: Some(Language::Dart),
        severity: Severity::Warn,
        principle: "typed errors",
        title: "`throw` as control flow",
    },
    Rule {
        code: "DA006",
        lang: Some(Language::Dart),
        severity: Severity::Warn,
        principle: "effects pushed outward",
        title: "direct `print` in library code",
    },
    Rule {
        code: "DA007",
        lang: Some(Language::Dart),
        severity: Severity::Warn,
        principle: "illegal states excluded by types",
        title: "null assertion (`!`) suppresses a real case",
    },
    Rule {
        code: "DA008",
        lang: Some(Language::Dart),
        severity: Severity::Warn,
        principle: "pure transformations",
        title: "in-place collection mutation",
    },
    Rule {
        code: "DA009",
        lang: Some(Language::Dart),
        severity: Severity::Warn,
        principle: "illegal states excluded by types",
        title: "`default:` arm defeats exhaustiveness",
    },
    Rule {
        code: "XX001",
        lang: None,
        severity: Severity::Warn,
        principle: "composition",
        title: "oversized module",
    },
    Rule {
        code: "XX002",
        lang: None,
        severity: Severity::Warn,
        principle: "explicit outputs",
        title: "long function body",
    },
];

pub fn rule(code: &str) -> Option<&'static Rule> {
    return RULES.iter().find(|rule| rule.code == code);
}
